/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface InvoiceInterface extends Interface {
  functions: {
    get_date_of_sale: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class Invoice extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Invoice;
  attach(addressOrName: string): Invoice;
  deployed(): Promise<Invoice>;

  on(event: EventFilter | string, listener: Listener): Invoice;
  once(event: EventFilter | string, listener: Listener): Invoice;
  addListener(eventName: EventFilter | string, listener: Listener): Invoice;
  removeAllListeners(eventName: EventFilter | string): Invoice;
  removeListener(eventName: any, listener: Listener): Invoice;

  interface: InvoiceInterface;

  functions: {
    get_date_of_sale(): Promise<BigNumber>;
  };

  get_date_of_sale(): Promise<BigNumber>;

  filters: {};

  estimate: {
    get_date_of_sale(): Promise<BigNumber>;
  };
}
